import type {
	ExtensionAPI,
	ExtensionContext,
} from "@earendil-works/pi-coding-agent";

const VERBS = [
	"Bitch im workin on it",
	"Hold your horses",
	"Summoning demons",
	"Asking my therapist",
	"Googling it like you should have",
	"Stealing code from Stack Overflow",
	"Pretending to be smart",
	"Having an existential crisis",
	"this is so sad. alexa play despacito",
	"in awe at the size of this file. absolute unit",
	"they don't think it be like it is but it do",
	"i have the power of god and anime on my side",
	"we have code at home. the code at home:",
	"it's giving... undefined behavior",
	"no thoughts. head empty. just vibes and semicolons",
	"the type checker said no. i said please. it said no again",
	"live laugh love except the code won't compile so just cry",
	"i showed you my PR please respond",
	"bro really said 'ship it' in production and meant it",
	"the code is giving main character energy and not in a good way",
	"every day we stray further from god's design patterns",
	"skill issue (the skill issue is mine)",
	"it compiled. i am not going to question why",
	"oh you're approaching me? i can't refactor your code without getting closer",
	"the function name is a lie. the comments are a lie. everything is a lie",
	"bestie this switch statement has 47 branches",
	"caught the bug in 4k",
	"gentlemen, it has been a privilege coding with you tonight",
	"i fear no man. but that regex... it scares me",
	"the audacity of this function to just. sit there. being O(n²)",
	"look at me. i am the maintainer now",
	"you miss 100% of the commits you don't push. - wayne gretzky. - michael scott",
	"to deploy, or not to deploy. that is the question. the answer is no",
	"i'm in this codebase and i don't like it",
	"the call is coming from inside the function",
	"you could not live with your own failure. where did that bring you? back to me",
	"trust the process. the process is panicking",
	"the floor is lava. the lava is your test suite",
	"tell me you wrote this at 4am without telling me you wrote this at 4am",
	"it's not a bug it's a surprise feature and i'm surprised",
	"congratulations you played yourself. and by you i mean me. i played myself",
	"understandable have a great compile error",
	"they asked me how i was doing and i said i'm fine but i'm not fine. the tests are red",
	"bold of you to assume this compiles",
	"anyway here's wonderwall.ts",
	"i don't have bugs. i have features that haven't been understood yet",
	"wake up babe new production issue just dropped",
	"and i oop. that was supposed to be immutable",
	"the function is long and full of terrors",
	"in this economy? you want me to write tests in this economy?",
	"if you or a loved one has been affected by legacy code. you may be entitled to financial compensation",
	"i'm not locked in here with your code. your code is locked in here with me",
	"we do a little refactoring. as a treat",
	"hear me out. what if we just... don't",
	"hello yes i'd like to report a crime. this function",
	"you want it done right or you want it done now? trick question you're getting neither",
	"things i trust more than this code: gas station sushi",
	"the real treasure was the compiler errors we got along the way",
	"it's giving 'i wrote this at 4am and now nobody can maintain it'",
	"we didn't start the fire. it was always burning since the build's been turning",
	"anyway so i started blasting. and by blasting i mean redeploying",
	"i am once again asking for your emotional support. the pipeline failed",
	"fun fact: this function has more lines than my will to live",
	"roses are red. violets are blue. unexpected token on line 32",
	"do you ever just look at code and immediately know the author was going through something",
	"this code was written by someone who hates the next person to read it. the next person is me",
	"the code giveth and the code taketh away. mostly it taketh",
	"houston we have a problem. several actually. like 47 of them",
	"the tailwind class names grow longer and my soul grows shorter",
	"z-index: 9999 and still not on top. incredible",
	"mobile first. except i forgot about mobile",
	"it's not a design system. it's vibes with border-radius",
	"the font is not the problem. the font is never the problem. it is always the font",
	"rewriting the css for the fourth time. as a treat",
	"box box. the deploy window is open",
	"checking telemetry for emotional damage",
	"purple sector in the profiler",
	"we are simply managing tyres and expectations",
	"if in doubt. undercut the technical debt",
	"that merge had no grip whatsoever",
	"pushing now. no further questions your honor",
	"drs enabled. i'm overtaking this bug",
	"no michael no no michael that was so not right. the ci exploded",
	"we went motor racing. unfortunately it was in production",
	"the strategy team is just me and bad ideas",
	"safety car deployed. the build failed but gently",
	"hunting the apex and the missing semicolon",
	"it is called a motor race. we went coding",
] as const;

function setRandomVerb(ctx: ExtensionContext): void {
	ctx.ui.setWorkingMessage(VERBS[Math.floor(Math.random() * VERBS.length)]);
}

export default function spinnerVerbsExtension(pi: ExtensionAPI): void {
	pi.on("session_start", (_event, ctx) => setRandomVerb(ctx));
	pi.on("turn_start", (_event, ctx) => setRandomVerb(ctx));
}
