#!/bin/bash

pgrep -x sxhkd > /dev/null || sxhkd &
setxkbmap de & 
$HOME/.config/polybar/launch.sh & 
nitrogen --restore &
lxqt-policykit-agent & 
picom --config .config/picom.conf --experimental-backends -f &



bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^6' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a Spotify desktop="^4"
bspc rule -a Pcmanfm desktop="^9"
bspc rule -a discord desktop="^3"
bspc rule -a App desktop="^5"
bspc rule -a Neutralino-linux_x64 desktop="^5" center=true
